create table if not exists mpa_ratings
(
    id   integer generated by default as identity
        primary key,
    name varchar(10) not null
);

create table if not exists films
(
    id               integer generated by default as identity
        primary key,
    name             varchar(255) not null,
    description      varchar(200),
    release_date     date         not null,
    duration_minutes integer      not null
        constraint films_duration_minutes_check
            check (duration_minutes > 0),
    mpa_rating_id    integer      not null
        constraint fk_films_mpa_rating
            references mpa_ratings
);

create table if not exists genres
(
    id   integer generated by default as identity
        primary key,
    name varchar(50) not null
);

create table if not exists film_genres
(
    film_id  integer not null
        references films
            on delete cascade,
    genre_id integer not null
        references genres,
    primary key (film_id, genre_id)
);

create table if not exists users
(
    id       integer generated by default as identity
        primary key,
    email    varchar(255) not null
        constraint email_unique
            unique,
    login    varchar(255) not null
        constraint login_unique
            unique,
    name     varchar(255) not null,
    birthday date
);

create table if not exists friendships
(
    id           integer generated by default as identity
        primary key,
    from_user_id integer not null
        references users
            on delete cascade,
    to_user_id   integer not null
        references users
            on delete cascade,
    constraint friendships_pk
        unique (from_user_id, to_user_id)
);

create table if not exists film_likes
(
    user_id    integer not null
        references users
            on delete cascade,
    film_id    integer not null
        references films
            on delete cascade,
    created_at timestamp default CURRENT_TIMESTAMP,
    unique (user_id, film_id)
);
